--- # ----------------------------------------------------

# Zeebe broker configuration file
# ! ! ! ! ! ! ! ! ! !
# In order to activate the settings in this file, please set the following environment variable:
# export SPRING_CONFIG_LOCATION='file:./config/zeebe.cfg.yaml'
# ! ! ! ! ! ! ! ! ! !

# Overview -------------------------------------------

# This file contains a complete list of available configuration options.

# Default values:
#
# When the default value is used for a configuration option, the option is
# commented out. You can learn the default value from this file

# The only deviation from the rule above is the exporters section.
# By default no exporters are configured. This file shows default/example values for configuring
# several exporters. To enable an exporter please uncomment the whole block and overwrite the settings.

# Conventions:
#
# Byte sizes
# For buffers and others must be specified as strings and follow the following
# format: "10U" where U (unit) must be replaced with KB = Kilobytes, MB = Megabytes or GB = Gigabytes.
# If unit is omitted then the default unit is simply bytes.
# Example:
# sendBufferSize = "16MB" (creates a buffer of 16 Megabytes)
#
# Time units
# Timeouts, intervals, and the likes, must be specified either in the standard ISO-8601 format used
# by java.time.Duration, or as strings with the following format: "VU", where:
#   - V is a numerical value (e.g. 1, 5, 10, etc.)
#   - U is the unit, one of: ms = Millis, s = Seconds, m = Minutes, or h = Hours
#
# Paths:
# Relative paths are resolved relative to the installation directory of the broker.
zeebe:
  broker:
    exporters:
      kafka:
        className: io.zeebe.exporters.kafka.KafkaExporter
        jarPath: exporters/zeebe-kafka-exporter-3.1.0-jar-with-dependencies.jar
        args:
          producer:
            # update this to point to your Kafka brokers
            servers: kafka_broker:29092
            config: |
              linger.ms=5
              buffer.memory=8388608
              batch.size=32768
              max.block.ms=5000
            records:
              # If a record value type is omitted in your configuration file,
              # it will fall back to whatever is configured in the defaults
              defaults: { type: "event", topic: zeebe }
